MvcAgenda/Models/Agenda.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace MvcAgenda.Models
{
    public class Agenda
    {
        public int ID { get; set; }

        [StringLength(100, MinimumLength = 10)]
        [Required]
        [Display(Name = "Class Name")]
        public string ClassName { get; set; }

        [Display(Name = "Class Date")]
        [DataType(DataType.Date)]
        public DateTime ReleaseDate { get; set; }

        [Required]
        [StringLength(50, MinimumLength = 10)]
        [Display(Name = "Hymn Name")]
        public string HymnName { get; set; }

        [RegularExpression(@"^[A-Z]+[a-zA-Z''-'\s]*$")]
        [Required]
        [StringLength(50, MinimumLength = 10)]
        [Display(Name = "First Prayer")]
        public string FirstPrayer { get; set; }

        [RegularExpression(@"^[A-Z]+[a-zA-Z''-'\s]*$")]
        [Required]
        [StringLength(50, MinimumLength = 10)]
        [Display(Name = "Last Prayer")]
        public string LastPrayer { get; set; }
    }
}

MvcAgenda/Models/AgendaHymnNameViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;

namespace MvcAgenda.Models
{
    public class AgendaHymnNameViewModel
    {
        public List<Agenda> agenda;
        public SelectList HymnName;
        public string agendaHymnName { get; set; }
    }
}

MvcAgenda/Models/SeedData.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using System;
using System.Linq;

namespace MvcAgenda.Models
{
    public static class SeedData
    {
        public static void Initialize(IServiceProvider serviceProvider)
        {
            using (var context = new MvcAgendaContext(
                serviceProvider.GetRequiredService<DbContextOptions<MvcAgendaContext>>()))
            {
                if (context.Agenda.Any())
                {
                    return;
                }

                context.Agenda.AddRange(
                     new Agenda
                     {
                         ClassName = "Introduction to the Doctrine and Covenants and Church History",
                         ReleaseDate = DateTime.Parse("2017-1-1"),
                         HymnName = "I Am a Child of God",
                         FirstPrayer = "Lizandro Conterini Coelho",
                         LastPrayer = "Regiane Silva Simão Coelho"
                     }
                );
                context.SaveChanges();
            }
        }
    }
}

MvcAgenda/Controllers/AgendaController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MvcAgenda.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;

namespace MvcAgenda.Controllers
{
    public class AgendaController : Controller
    {
        private readonly MvcAgendaContext _context;

        public AgendaController(MvcAgendaContext context)
        {
            _context = context;
        }

        // Requires using Microsoft.AspNetCore.Mvc.Rendering;
        public async Task<IActionResult> Index(string agendaHymnName, string searchString)
        {
            // Use LINQ to get list of hymns name.
            IQueryable<string> HymnNameQuery = from m in _context.Agenda
                                               orderby m.HymnName
                                               select m.HymnName;

            var agenda = from m in _context.Agenda
                         select m;

            if (!String.IsNullOrEmpty(searchString))
            {
                agenda = agenda.Where(s => s.ClassName.Contains(searchString));
            }

            if (!String.IsNullOrEmpty(agendaHymnName))
            {
                agenda = agenda.Where(x => x.HymnName == agendaHymnName);
            }

            var agendaHymnNameVM = new AgendaHymnNameViewModel();
            agendaHymnNameVM.HymnName = new SelectList(await HymnNameQuery.Distinct().ToListAsync());
            agendaHymnNameVM.agenda = await agenda.ToListAsync();

            return View(agendaHymnNameVM);
        }

        [HttpPost]
        public string Index(string searchString, bool notUsed)
        {
            return "From [HttpPost]Index: filter on " + searchString;
        }

        // GET: Agenda/Details
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var agenda = await _context.Agenda
                .SingleOrDefaultAsync(m => m.ID == id);
            if (agenda == null)
            {
                return NotFound();
            }

            return View(agenda);
        }

        // GET: Agenda/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Agenda/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,ClassName,ReleaseDate,HymnName,FirstPrayer,LastPrayer")] Agenda agenda)
        {
            if (ModelState.IsValid)
            {
                _context.Add(agenda);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(agenda);
        }

        // GET: Agenda/Edit
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var agenda = await _context.Agenda.SingleOrDefaultAsync(m => m.ID == id);
            if (agenda == null)
            {
                return NotFound();
            }
            return View(agenda);
        }

        // POST: Agenda/Edit
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,ClassName,ReleaseDate,HymnName,FirstPrayer,LastPrayer")] Agenda agenda)
        {
            if (id != agenda.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(agenda);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AgendaExists(agenda.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            return View(agenda);
        }

        // GET: Agenda/Delete
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var agenda = await _context.Agenda
                .SingleOrDefaultAsync(m => m.ID == id);
            if (agenda == null)
            {
                return NotFound();
            }

            return View(agenda);
        }

        // POST: Agenda/Delete
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var agenda = await _context.Agenda.SingleOrDefaultAsync(m => m.ID == id);
            _context.Agenda.Remove(agenda);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private bool AgendaExists(int id)
        {
            return _context.Agenda.Any(e => e.ID == id);
        }
    }
}

MvcAgenda/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace MvcAgenda.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "";

            return View();
        }

        public IActionResult Error()
        {
            return View();
        }
    }
}

MvcAgenda/Views/Agenda/Create.cshtml
@model MvcAgenda.Models.Agenda

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<form asp-action="Create">
    <div class="form-horizontal">
        <h4>Agenda</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="ClassName" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="ClassName" class="form-control" />
                <span asp-validation-for="ClassName" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="ReleaseDate" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="ReleaseDate" class="form-control" />
                <span asp-validation-for="ReleaseDate" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="HymnName" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="HymnName" class="form-control" />
                <span asp-validation-for="HymnName" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="FirstPrayer" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="FirstPrayer" class="form-control" />
                <span asp-validation-for="FirstPrayer" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="LastPrayer" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="LastPrayer" class="form-control" />
                <span asp-validation-for="LastPrayer" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MvcAgenda/Views/Agenda/Delete.cshtml
@model MvcAgenda.Models.Agenda

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Agenda</h4>
    <hr />
    <dl class="dl-horizontal">
        <input type="hidden" asp-for="ID" />
        <dt>
            @Html.DisplayNameFor(model => model.ClassName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ClassName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ReleaseDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ReleaseDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.HymnName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.HymnName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.FirstPrayer)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FirstPrayer)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.LastPrayer)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.LastPrayer)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            <a asp-action="Index">Back to List</a>
        </div>
    </form>
</div>

MvcAgenda/Views/Agenda/Details.cshtml
@model MvcAgenda.Models.Agenda

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Agenda</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ClassName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ClassName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ReleaseDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ReleaseDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.HymnName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.HymnName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.FirstPrayer)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FirstPrayer)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.LastPrayer)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.LastPrayer)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

MvcAgenda/Views/Agenda/Edit.cshtml
@model MvcAgenda.Models.Agenda

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<form asp-action="Edit">
    <div class="form-horizontal">
        <h4>Agenda</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="ID" />
        <div class="form-group">
            <label asp-for="ClassName" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="ClassName" class="form-control" />
                <span asp-validation-for="ClassName" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="ReleaseDate" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="ReleaseDate" class="form-control" />
                <span asp-validation-for="ReleaseDate" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="HymnName" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="HymnName" class="form-control" />
                <span asp-validation-for="HymnName" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="FirstPrayer" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="FirstPrayer" class="form-control" />
                <span asp-validation-for="FirstPrayer" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="LastPrayer" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="LastPrayer" class="form-control" />
                <span asp-validation-for="LastPrayer" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MvcAgenda/Views/Agenda/Index.cshtml
@model MvcAgenda.Models.AgendaHymnNameViewModel

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>

<form asp-controller="Agenda" asp-action="Index" method="get">
    <p>
        <select asp-for="agendaHymnName" asp-items="Model.HymnName">
            <option value="">Hymn Name</option>
        </select>
        
        Class Name: <input type="text" name="SearchString">
        <input type="submit" value="Filter" />
    </p>
</form>

<table class="table">
    <thead>
        <tr>
                <th>
                    @Html.DisplayNameFor(model => model.agenda[0].ClassName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.agenda[0].ReleaseDate)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.agenda[0].HymnName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.agenda[0].FirstPrayer)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.agenda[0].LastPrayer)
                </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.agenda) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ClassName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ReleaseDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.HymnName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FirstPrayer)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastPrayer)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.ID">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
            </td>
        </tr>
        }
    </tbody>
</table>

MvcAgenda/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>I am an online student</p>
<p>I am studying in Brigham Young University - Idaho</p>
<p>This a simple agenda for use in School Sunday Class.</p>
<p>We must fill the fields for Name and Date for Class, Hymn Name, and First and Last Prayer.</p>

MvcAgenda/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    231 Paulo Macarini<br />
    Curitiba, Paraná<br />
    Brazil 82630-572<br />
    <abbr title="Phone">Phone:</abbr>
    55 41 3257.8824
</address>

<address>
    <strong>Support:</strong> <a href="mailto:edvaldomelo@byui.edu">edvaldomelo@byui.edu</a><br />
    <strong>Marketing:</strong> <a href="mailto:familiamelo@gmail.com">familiamelo@gmail.com</a>
</address>

MvcAgenda/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
        <li data-target="#myCarousel" data-slide-to="3"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/banner1.svg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how to build ASP.NET apps that can run anywhere.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner2.svg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    There are powerful new features in Visual Studio for building modern web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner3.svg" alt="Package Management" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Bring in libraries from NuGet, Bower, and npm, and automate tasks using Grunt or Gulp.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525029&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner4.svg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-3">
        <h2>Application uses</h2>
        <ul>
            <li>Sample pages using ASP.NET Core MVC</li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518004">Bower</a> for managing client-side libraries</li>
            <li>Theming using <a href="https://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>How to</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398600">Add a Controller and View</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699318">Add client packages using Bower.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Overview</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Run & Deploy</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure Web Apps</a></li>
        </ul>
    </div>
</div>

MvcAgenda/Views/Shared/_Layout.cshtml
@inject Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet JavaScriptSnippet
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Agenda App</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    @Html.Raw(JavaScriptSnippet.FullScript)
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Agenda" asp-action="Index" class="navbar-brand">Agenda</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - Agenda</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>